[package]
name = "csv_play"
version = "0.1.0"
authors = ["Yury Liavitski <yury.liavitski@il111.ice.local>"]

[dependencies]
csv = "1.0.0-beta.5"
serde_json = "1.0"
chrono = "0.4"

[profile.release]
debug = true